language: node_js

node_js:
    - '0.10'

services:
    - docker

before_script:
    - npm -g install npm@latest-2
    - git clone https://${GITHUB_AUTH}:x-oauth-basic@github.com/juttle/juttle.git
    - pushd juttle ; npm install ; npm link ; popd
    - ./scripts/docker.sh start

script:
    - export NODE_PATH="$(dirname `which node`)/../lib/node_modules"
    - npm test

after_script:
    - ./scripts/docker.sh stop
