language: node_js

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

before_install:
  - export CXX="g++-4.8"

node_js:
    - '4.2'
    - '5.0'

services:
    - docker

before_script:
    - npm install juttle@0.4.x
    - ./scripts/docker.sh start

script:
    - npm run-script -s cov

after_script:
    - ./scripts/docker.sh stop
