language: node_js

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - g++-4.8

before_install:
  - export CXX="g++-4.8"

node_js:
    - '4.2'
#    - '5.0'

env:
    - INFLUX_VERSION=0.9 JUTTLE_PACKAGE=juttle/juttle
#    - INFLUX_VERSION=0.9 JUTTLE_PACKAGE=juttle@0.5.x
    - INFLUX_VERSION=0.10 JUTTLE_PACKAGE=juttle/juttle
#    - INFLUX_VERSION=0.10 JUTTLE_PACKAGE=juttle@0.5.x

services:
    - docker

before_script:
    - rm -rf node_modules/juttle
    - npm install $JUTTLE_PACKAGE
    - pushd node_modules/juttle; npm install; popd
    - ./scripts/docker.sh start

script:
    - npm run-script -s cov

after_script:
    - ./scripts/docker.sh stop
