language: node_js

node_js:
    - '0.10'

before_script:
    - git clone https://${GITHUB_AUTH}:x-oauth-basic@github.com/juttle/juttle.git
    - pushd juttle ; npm install ; npm link ; popd

script:
    - export NODE_PATH="$(dirname `which node`)/../lib/node_modules"
    - npm test
